//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using System.Runtime.Serialization;
using Core.Entities;

namespace DataAccess.UserModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMapping:EntityTypeConfiguration<Core.Entities.User.Client>
    {
        
        public ClientMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.FirstName).IsRequired()
    .HasMaxLength(100);
    
    
     
                    this.Property(t => t.LastName).IsRequired()
    .HasMaxLength(100);
    
    
     
                    this.Property(t => t.Identification).IsRequired()
    .HasMaxLength(50);
    
    
     
                    this.Property(t => t.PhoneNumber).IsRequired()
    .HasMaxLength(50);
    
    
    
                this.ToTable("Client","dbo");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.IdStatus).HasColumnName("IdStatus");
        this.Property(t => t.FirstName).HasColumnName("FirstName");
        this.Property(t => t.LastName).HasColumnName("LastName");
        this.Property(t => t.Identification).HasColumnName("Identification");
        this.Property(t => t.PhoneNumber).HasColumnName("PhoneNumber");
        this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");
        this.Property(t => t.UpdateDate).HasColumnName("UpdateDate");
    
                // Relationships
                this.HasRequired(t => t.Status)
                    .WithMany(t => t.Client)
                    .HasForeignKey(d => d.IdStatus);
    
    
    
        }
    
        
        
        
        
        
        
        
        
    
        
        
    }
}
