//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using System.Runtime.Serialization;
using Core.Entities;

namespace DataAccess.UserModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMapping:EntityTypeConfiguration<Core.Entities.User.Product>
    {
        
        public ProductMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.Name).IsRequired()
    .HasMaxLength(100);
    
    
    
                this.ToTable("Product","dbo");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.IdStatus).HasColumnName("IdStatus");
        this.Property(t => t.Name).HasColumnName("Name");
        this.Property(t => t.UnitValue).HasColumnName("UnitValue");
        this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");
        this.Property(t => t.UpdateDate).HasColumnName("UpdateDate");
    
                // Relationships
                this.HasRequired(t => t.Status)
                    .WithMany(t => t.Product)
                    .HasForeignKey(d => d.IdStatus);
    
    
    
        }
    
        
        
        
        
        
        
    
        
        
    }
}
