//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------




using System.Data.Entity.ModelConfiguration;
using System.Runtime.Serialization;
using Core.Entities;

namespace DataAccess.UserModule.UnitOfWork.Mapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMapping:EntityTypeConfiguration<Core.Entities.User.User>
    {
        
        public UserMapping()
        {
                // Primary Key
                this.HasKey(t => t.Id);
    
    
                // Properties
     
                    this.Property(t => t.FullName).IsRequired()
    .HasMaxLength(200);
    
    
     
                    this.Property(t => t.Email).HasMaxLength(200);
    
    
     
                    this.Property(t => t.PhoneNumber).HasMaxLength(200);
    
    
     
                    this.Property(t => t.UserName).IsRequired()
    .HasMaxLength(100);
    
    
     
                    this.Property(t => t.Password).IsRequired();
    
    
     
                    this.Property(t => t.Identification).IsRequired()
    .HasMaxLength(50);
    
    
    
                this.ToTable("User","dbo");
        this.Property(t => t.Id).HasColumnName("Id");
        this.Property(t => t.IdStatus).HasColumnName("IdStatus");
        this.Property(t => t.FullName).HasColumnName("FullName");
        this.Property(t => t.Email).HasColumnName("Email");
        this.Property(t => t.PhoneNumber).HasColumnName("PhoneNumber");
        this.Property(t => t.UserName).HasColumnName("UserName");
        this.Property(t => t.Password).HasColumnName("Password");
        this.Property(t => t.Identification).HasColumnName("Identification");
        this.Property(t => t.CreatedDate).HasColumnName("CreatedDate");
        this.Property(t => t.UpdateDate).HasColumnName("UpdateDate");
    
                // Relationships
                this.HasRequired(t => t.Status)
                    .WithMany(t => t.User)
                    .HasForeignKey(d => d.IdStatus);
    
    
    
        }
    
        
        
        
        
        
        
        
        
        
        
    
        
        
    }
}
