//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.User
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Client = new HashSet<Client>();
            this.Product = new HashSet<Product>();
            this.Transaction = new HashSet<Transaction>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<Transaction> Transaction { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
