//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Entities.User
{
    using System;
    using System.Collections.Generic;
    
    public partial class UaletDetailStatements
    {
        public long Id { get; set; }
        public long FinancialStatementsDetailId { get; set; }
        public long UaletAccountId { get; set; }
        public string AccountNumber { get; set; }
        public decimal InitialBalance { get; set; }
        public decimal EndBalance { get; set; }
        public decimal Additions { get; set; }
        public decimal Remove { get; set; }
        public decimal TotalReturns { get; set; }
        public decimal To30Days { get; set; }
        public decimal To60Days { get; set; }
        public decimal To90Days { get; set; }
        public decimal To180Days { get; set; }
        public decimal To360Days { get; set; }
        public decimal CurrentYear { get; set; }
        public decimal LastTwoYear { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual UaletAccount UaletAccount { get; set; }
    }
}
