//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.UserModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdProduct { get; set; }
        public int IdDocumentType { get; set; }
        public int IdStatus { get; set; }
        public int Quantity { get; set; }
        public decimal TotalValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Product Product { get; set; }
        public virtual State State { get; set; }
    }
}
