//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccess.UserModule.UnitOfWork
{
    using System.Data.Entity;
    using Core.Entities.User;
    using Data.Common.Definition;
    
    public partial interface IUserContext : IQueryableUnitOfWork
    {
        DbSet<Client> Client { get; set; }
        DbSet<Product> Product { get; set; }
        DbSet<Status> Status { get; set; }
        DbSet<Transaction> Transaction { get; set; }
        DbSet<TransactionType> TransactionType { get; set; }
        DbSet<User> User { get; set; }
    }
}
