//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.UserModule.UnitOfWork
{
    using Core.Entities.User;
    using System.Data.Entity;
    using DataAccess.UserModule.UnitOfWork.Mapping;
    
    public partial class UserContext : Data.Common.Implementation.UnitOfWork, IUserContext
    {
        public UserContext()
            : base("name=UserModelEntities")
        {
    	    Database.SetInitializer<UserContext>(null);
        }
    
     
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
        public virtual DbSet<User> User { get; set; }
    
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
         base.OnModelCreating(modelBuilder);
    
        modelBuilder.Configurations.Add(new ClientMapping());
        modelBuilder.Configurations.Add(new ProductMapping());
        modelBuilder.Configurations.Add(new StatusMapping());
        modelBuilder.Configurations.Add(new TransactionMapping());
        modelBuilder.Configurations.Add(new TransactionTypeMapping());
        modelBuilder.Configurations.Add(new UserMapping());
    }
    
    
    }
}
